version: '3.3'

services:
  # Mysql
  mysql-0:
    container_name: "mysql-0"
    image: mysql:8.0.20
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_HOST: '%'
      MYSQL_ROOT_PASSWORD: secret1234
      MYSQL_DATABASE: todo
      MYSQL_USER: todouser
      MYSQL_PASSWORD: secret1234
      LANG: C.UTF-8
    volumes:
      - ./scripts/:/docker-entrypoint-initdb.d
    entrypoint: [ '/entrypoint.sh', '--default-authentication-plugin=mysql_native_password' ]
    security_opt:
      - seccomp:unconfined

  # Jaeger
  jaeger-all-in-one:
    image: jaegertracing/all-in-one
    container_name: jaeger
    ports:
      - "16686:16686"
      - "14268:14268"
